kind: Deployment
image:
  pullPolicy: "Always"
replicas: 1
resources:
  limits:
    memory: 2048Mi
    cpu: 2000m
  requests:
    memory: 256Mi
    cpu: 10m

#nodeSelector:
#  kubernetes.io/hostname: k8s-node2

#***java && app 环境变量设置
env: 
  - name: "JAVA_OPTS"
    value: "-Xmx2048M -Xms1024M -Xss256k -Duser.timezone=Asia/Shanghai"
  - name: "JAVA_OPT_EXT"
    value: ""
  - name: "APP_OPTS"
    value: "--spring.profiles.active=uat"

envFrom:
  #- configMapRef:
  #  name: env-config

service:
  type: ClusterIP                     #Service type设置 (可以设置为ClusterIP、NodePort、None)
  labels: 
    svcEndpoints: actuator
  annotations: {}
  ports: 
    - name: server
      port: 9080
      targetPort: 9080
      protocol: TCP
#      nodePort: 9080

mount:
  volumeMounts:
#    - name: applogs
#      mountPath: /app/logs/platform-factory-project
  volumes:
#    - name: applogs
#      nfs:
#        server: 192.168.0.159
#        path: /data/k8s/factory/platform-factory-project
