spring:
  datasource:
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:mem:semantic;DATABASE_TO_UPPER=false;QUERY_TIMEOUT=30
#    username: root
#    password: semantic
#    url: jdbc:mysql://wxxinsoft.gnway.org:10913/supersonic?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowMultiQueries=true
#    username: root
#    password: 123456
    url: jdbc:mysql://192.168.2.201:30506/supersonic?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowMultiQueries=true
    username: platformsuper
    password: '!Sql_Pass@1!'
    driver-class-name: com.mysql.jdbc.Driver
  sql:
    init:
      schema-locations: classpath:db/schema-h2.sql
      data-locations: classpath:db/data-h2.sql
  h2:
    console:
      path: /h2-console/semantic
      enabled: true